### ISSUE TITLE
Realización de mockups para la interacción básica del sistema.

### ISSUE THREAD

**Issue by Flor-AC** [Flor-AC/reto_IBM#2]
Se anexan los siguientes mockups.

**Comment by Luis501Angel** [comment]
En la primera pantalla se usara la CURP para realizar el inicio de sesión
![1_Home](https://user-images.githubusercontent.com/42681133/115644627-860a5780-a2e4-11eb-890f-af985574d5d1.png)
 Posteriormente se solicitara el escaneo de la INE de la parte de adelante y de atras, para poder realizar una confirmación de identidad
![1-1_Solicitud de escaneo](https://user-images.githubusercontent.com/42681133/115644694-9de1db80-a2e4-11eb-8bbb-77d51faf888b.png)
Al iniciar podremos observar nuestro perfil desde donde podremos votar y podremos obtener actualizacion de parte del INE mediante mensajes, podremos visualizar a los candidatos participantes
![1-2_Inicio](https://user-images.githubusercontent.com/42681133/115644795-c8cc2f80-a2e4-11eb-8317-08be4dc47bcc.png)
Al seleccionar en ver más podremos obtener información sobre la candidatura con las propuestas
![1-4_Candidato - Ver mas](https://user-images.githubusercontent.com/42681133/115644832-d84b7880-a2e4-11eb-94c1-f2f3fb6fb414.png)
Finalmente para realizar la votación se pedira activar la **ubicación, camara encendida en el momento, microfono** para garantizar un voto seguro
![1-3_Votar](https://user-images.githubusercontent.com/42681133/115644887-f1ecc000-a2e4-11eb-8fa1-4279f90aa08b.png)
